"""“Initial”

Revision ID: 5db1be6524c4
Revises: 
Create Date: 2022-11-21 11:47:30.227226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5db1be6524c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelf',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', 'DELETED', name='shelfstatuses'), nullable=False),
    sa.Column('type', sa.Enum('INN', 'OUT', 'TRASH', 'LOSTFOUND', 'STORE', name='shelftype'), nullable=False),
    sa.Column('storage_tags', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('vars', sa.JSON(), nullable=True),
    sa.Column('lsn', sa.BigInteger(), nullable=False),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_shelf_barcode'), 'shelf', ['barcode'], unique=True)
    op.create_index(op.f('ix_shelf_company_id'), 'shelf', ['company_id'], unique=False)
    op.create_table('storage_type',
    sa.Column('storage_type_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('lsn', sa.BigInteger(), nullable=False),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('storage_type_id', 'id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_storage_type_code'), 'storage_type', ['code'], unique=True)
    op.create_index(op.f('ix_storage_type_company_id'), 'storage_type', ['company_id'], unique=False)
    op.create_table('store',
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DISABLED', 'ACTIVE', 'CLOSED', name='storestatus'), nullable=False),
    sa.Column('type', sa.Enum('DARKSTORE', 'SHOP', 'DC', name='storetype'), nullable=False),
    sa.Column('vars', sa.JSON(), nullable=True),
    sa.Column('lsn', sa.BigInteger(), nullable=False),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_store_company_id'), 'store', ['company_id'], unique=False)
    op.create_index(op.f('ix_store_external_id'), 'store', ['external_id'], unique=True)
    op.create_table('users',
    sa.Column('password', sa.Unicode(length=255), nullable=False),
    sa.Column('email', sa.Unicode(length=255), nullable=False),
    sa.Column('nickname', sa.Unicode(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('lsn', sa.BigInteger(), nullable=False),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname')
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_store_external_id'), table_name='store')
    op.drop_index(op.f('ix_store_company_id'), table_name='store')
    op.drop_table('store')
    op.drop_index(op.f('ix_storage_type_company_id'), table_name='storage_type')
    op.drop_index(op.f('ix_storage_type_code'), table_name='storage_type')
    op.drop_table('storage_type')
    op.drop_index(op.f('ix_shelf_company_id'), table_name='shelf')
    op.drop_index(op.f('ix_shelf_barcode'), table_name='shelf')
    op.drop_table('shelf')
    # ### end Alembic commands ###
